# Generated by Django 5.2.4 on 2025-07-21 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="notes/images",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("personal", "Личная запись"),
                            ("work", "Рабочая запись"),
                            ("defect_statement", "Дефектная ведомость"),
                            ("hidden_act", "Акт скрытых работ"),
                        ],
                        max_length=20,
                        verbose_name="Тип записи",
                    ),
                ),
                (
                    "mood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Настроение"
                    ),
                ),
                (
                    "is_private",
                    models.BooleanField(default=True, verbose_name="Приватная"),
                ),
                (
                    "object_name",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="Название объекта"
                    ),
                ),
                (
                    "contractor",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Подрядчик"
                    ),
                ),
                (
                    "customer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Заказчик"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        blank=True, upload_to="work_docs/", verbose_name="Документ"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Адрес объекта"
                    ),
                ),
                (
                    "act_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер акта"
                    ),
                ),
                (
                    "inspection_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата проверки"
                    ),
                ),
                (
                    "statement_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Номер ведомости"
                    ),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата утверждения"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Утвердил"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись",
                "verbose_name_plural": "Записи",
                "ordering": ["-created_at"],
            },
        ),
    ]
