# Generated by Django 5.2.4 on 2025-07-21 16:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="defect_images/", verbose_name="Фото дефекта"
                    ),
                ),
                (
                    "defect_number",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Номер дефекта",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание"
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_images",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение дефекта",
                "verbose_name_plural": "Изображения дефектов",
                "ordering": ["note", "defect_number"],
                "indexes": [
                    models.Index(
                        fields=["note", "defect_number"],
                        name="notes_defec_note_id_fb1c41_idx",
                    )
                ],
            },
        ),
    ]
