# Generated by Django 5.2.4 on 2025-07-23 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_defectimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="act_number",
        ),
        migrations.RemoveField(
            model_name="note",
            name="contractor",
        ),
        migrations.RemoveField(
            model_name="note",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="note",
            name="document",
        ),
        migrations.RemoveField(
            model_name="note",
            name="inspection_date",
        ),
        migrations.AddField(
            model_name="note",
            name="defects",
            field=models.ManyToManyField(
                blank=True, limit_choices_to={"note_type": "defect"}, to="notes.note"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="approval_date",
            field=models.DateField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Дата утверждения",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(blank=True, verbose_name="Содержание"),
        ),
        migrations.AlterField(
            model_name="note",
            name="note_type",
            field=models.CharField(
                choices=[
                    ("personal", "Личная запись"),
                    ("work", "Рабочая запись"),
                    ("defect_statement", "Дефектная ведомость"),
                ],
                max_length=20,
                verbose_name="Тип записи",
            ),
        ),
        migrations.CreateModel(
            name="NoteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="note_images/", verbose_name="Фото"),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Описание"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="notes.note",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DefectImage",
        ),
    ]
