# Generated by Django 5.2.4 on 2025-07-23 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_remove_note_act_number_remove_note_contractor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="approval_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата утверждения"
            ),
        ),
    ]
