# Generated by Django 5.2.4 on 2025-07-23 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_alter_note_approval_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="defects/%Y/%m/%d/", verbose_name="Фото дефекта"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание дефекта"),
                ),
                (
                    "required_work",
                    models.TextField(blank=True, verbose_name="Необходимые работы"),
                ),
                (
                    "repair_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="Срок устранения"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "note",
                    models.ForeignKey(
                        limit_choices_to={"note_type": "defect"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defect_images",
                        to="notes.note",
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение дефекта",
                "verbose_name_plural": "Изображения дефектов",
                "ordering": ["created_at"],
            },
        ),
        migrations.DeleteModel(
            name="NoteImage",
        ),
    ]
