# Generated by Django 5.2.4 on 2025-07-23 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_defectimage_delete_noteimage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DefectInStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "defect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="notes.note"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="DefectStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название ведомости"),
                ),
                (
                    "statement_number",
                    models.CharField(max_length=50, verbose_name="Номер ведомости"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата утверждения"
                    ),
                ),
                (
                    "approved_by",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Утвердил"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "defects",
                    models.ManyToManyField(
                        limit_choices_to={"note_type": "defect"},
                        through="notes.DefectInStatement",
                        to="notes.note",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="defectinstatement",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.defectstatement"
            ),
        ),
    ]
